FROM golang:1.25.2 AS builder
WORKDIR /upload_service_batch
ENV GOPRIVATE=github.com/arunshankar19
COPY go.mod go.mod
COPY go.sum go.sum
RUN --mount=type=secret,id=netrc \
    cp /run/secrets/netrc ~/.netrc && \
    chmod 600 ~/.netrc && \
    go mod download
COPY . .
RUN GOOS=linux CGO_ENABLED=0 go build -o upload-service-batch ./batch-app/

FROM alpine:3.22
WORKDIR /upload_service_batch
COPY --from=builder /upload_service_batch/upload-service-batch .
CMD ["./upload-service-batch"]
